# Generated by Django 5.2.6 on 2025-09-30 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptions',
            name='last_notified',
            field=models.DateField(auto_now_add=True),
        ),
    ]
