# Generated by Django 5.2.6 on 2025-09-30 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_subscriptions_last_notified'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subscriptions',
            unique_together={('user', 'city')},
        ),
    ]
