# Generated by Django 5.2.6 on 2025-10-06 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_subscriptions_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptions',
            name='last_notified',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
