# Generated by Django 5.2.6 on 2025-10-06 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_subscriptions_last_notified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptions',
            name='precipitation',
        ),
        migrations.AddField(
            model_name='subscriptions',
            name='precipitation_Probability',
            field=models.BooleanField(default=True),
        ),
    ]
