# Generated by Django 5.2.6 on 2025-10-06 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_subscriptions_precipitation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriptions',
            old_name='precipitation_Probability',
            new_name='precipitationProbability',
        ),
    ]
