# Generated by Django 5.2.6 on 2025-10-09 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_precipitation_probability_subscriptions_precipitationprobability'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriptions',
            old_name='precipitationProbability',
            new_name='precipitation_probability',
        ),
    ]
